We are starting the understanding the labrary of numpy

In [1]:
import numpy as np

In numpy, we are going to study two things.
1. Creating the array 
2. Performing the operation on array

In [2]:
# It will retrun the current version 
np.__version__

'2.4.6'

To create an array,
Syntax : var=np.array(pre_var)

In [3]:
l=[5,10,15,20]
type(l)

arr1=np.array(l)
type(arr1) # we can check the data type of the var


numpy.ndarray

In [4]:
arr2=np.array([12,14,272,7])
arr2

array([ 12,  14, 272,   7])

In [5]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

DIFFERNCE BETWEEN LIST AND ARRAY.

1. 
LIST : It is collaction of homogenous and heterogenous data inclosed between square braces []. 
Array : It is collection of only homogenous data inclosed between square braces[].

2. 
LIST : We can perform limited operation on list.
ARRAY : We can perform almost all operations on array.

3. 
LIST : It stores the data in discontinous memory allocation. 
ARRAY : It stores the data in continous memory allocation.

4. 
LIST : Acessing of values is slow in list.
ARRAY : Accessing of values is fast in list.

In [6]:
arr3=np.array((5678,983,True,False,2-3j,"str",{1,2,3,4},{"key":1}))
type(arr3[-1])


dict

Priority of datatype in numpy :   bool --> int(int64) --> float(float64) --> complex(complex128) --> str(U64) --> object

In [7]:
l1=[1,2,3,4,5,6]
l2=[7,8,9,10,11,12]
a1=np.array((2,4,6,8,10))
a2=np.array((12,14,16,18,20))


In [8]:
l1+l2 # Concatenate two list 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [9]:
a1+a2 # We can add two array element by element 

array([14, 18, 22, 26, 30])

In [10]:
l1-l2 # we can subtract list beacause this oepration in python list 
a1-a2 # we can subtract the both array because array execute element by element 


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
# Types od array 
# 1. Uni- dimentional array (1D)
# 2. Bi- dimenional array (2D)
# 3. Multi - dimentional array(3D)



In [ ]:
# Uni-dimensional array 
# np.array([1,2,3,2,1])

# Bi-dimesional array
# np.array([[1,2,3],[4,5,6]])

# Multi-dimesional array 
# np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 5,  6,  7],
        [ 8,  9, 10]]])

In [ ]:
np.array([[np.random.randint(1,100,3)],[np.random.randint(1,100,3)],[np.random.randint(1,100,3)]])

array([[[65, 95, 18]],

       [[99, 12, 11]],

       [[10, 58,  4]]], dtype=int32)

In [ ]:
# np.arange(SV,EV,UP): It will create 1D array consist of integers between specified limits.  

np.arange(11,25,1)
np.arange(11,21)
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
# CREATE AN 1D ARRAY CONSIST OF 1 TO 8.
n=np.arange(1,8)
# np.array(n) 
# OR 
# CREATE AN 1D ARRAY CONSIST OF 1 TO 24.

# np.array([np.arange(1,5),np.arange(2,6)])



array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# To convert 1D array into 2D  array.

""" using reshape (r,c) to convert into 2d  array"""
n=np.arange(0,12) # 2D array after using reshape functions
# n.reshape(2,4) 
a=n.reshape(3,4) 


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# TO convert 1D arrary into 3D array.
"""
Using reshape(r,c,d) to convert into 3d array.
where d--> no. of elements should present in inner array.
"""
c=np.arange(1,25).reshape(2,3,4)
# np.arange(1,13).reshape(2,2,3)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
np.arange(1,37).reshape(2,6,3)
np.arange(1,37).reshape(2,3,6)
np.arange(1,37).reshape(3,2,6)


array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]]])

In [ ]:
# Var.ndim : It will return the dimension of an array.
# a=np.arange(1,13)
# b=a.reshape(3,4) 
# c=np.arange(1,25).reshape(2,3,4)

# a.ndim
# b.ndim
# c.ndim


# var.shape : It will return, 1D-no. of elements in array , 2D- (no. of rows and no. of columns) and 3D - (no. of rows, no. of columns, no. of depth)
# a.shape
# b.shape
# c.shape 

# np.linspace(SV,EV,NO_OF_VALUES)
# np.linspace(5,15,7)
# np.linspace(1,5,3)
# np.linspace(1,5,7)
# np.linspace(1,2,5)

array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        ])

In [ ]:
# np.zeros():

# 1. np.zeros(values):- It is used to create 1D array consists of zeros.
np.zeros(5)

# 2. np.zeros(r,c) :- It is used to create 2D array consists of Zeros.
np.zeros((3,4))

# 3. np.zeros(r,c,d):- It is  used to create 3D array which consists of zeros.       
np.zeros((3,4,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [ ]:
# np.random.randint(SV,EV,N_V):
np.random.randint(1,100,15)


# np.array([[np.random.randint(1,100,3)],[np.random.randint(1,100,3)],[np.random.randint(1,100,3)]])
# np.random.randint(1,100)

array([68, 69, 95, 82, 67, 14, 63, 15,  3, 56, 31, 87, 31, 32, 93],
      dtype=int32)

In [ ]:
# np.random.rand(no_of_values): it will create an 1D array.



np.random.rand(5)

array([0.57660146, 0.21027189, 0.96049281, 0.19810036, 0.81161158])

In [ ]:
# It will create an 1D array consists of n number of values bwtween -infinity to infinity but mostly it will return values b/t -3 and 3.
np.random.randn(12) 

array([ 1.30454079, -1.14993238, -1.14307757,  0.40481373,  0.33403989,
       -0.3939657 , -0.54994496,  0.74133748, -0.54582821, -1.53713528,
        0.72636232,  0.4940844 ])

In [ ]:
a=np.arange(1,13)
b=a.reshape(3,4)
c=a.reshape(3,2,2)
c

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
"""3D-array"""
# 12-->c[2][1][1]
# 8-->c[1][1][1]
# 9-->c[2][0][0]
# 3-->c[0][1][0]
# [ 7,  8]-->c[1][1]

np.int64(3)

In [ ]:
# Aggregation Function :
#np.sum(var)-- Sum of all the values
#np.min(var)-- smallest values 
#np.max(var)-- largest values
#np.mean(var)--average value
#np.std(var)-- standard daviation

np.sum(a)
np.min(a)
np.max(a)
np.mean(a)
np.std(a)

np.float64(3.452052529534663)

In [ ]:
# np.identity(n) : 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# np.eye(n) and np.eye(r,c): It will create identity matrix, but we can modify the number of columns in it.
np.eye(4,3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
# np.full(no_values,values): It will fill whole array with the value.
np.full((10,10)," ")
np.full(2,"hii")

array(['hii', 'hii'], dtype='<U3')

In [ ]:
# np.where(condition, True_result, False_result):  It is used to filter the conditions.
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# if the number is even then replace  it with "even" or else replace it with "odd".
np.where(a%2==0,"even","odd")

array(['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even'], dtype='<U4')

In [ ]:
# convert the interger  with 0 which are multiple of 5, and make other values True.
np.where(b%5==0,0,True)

array([[1, 1, 1, 1],
       [0, 1, 1, 1],
       [1, 0, 1, 1]])

In [ ]:
# Replace the value which are multiple of 7 with 1, and other keep as it is 
np.where(c%7==0,1,c)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 1,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
# we create a 3rd array.
z=np.arange(1,25)
z=z.reshape(2,3,4)
z

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
# Replace value with 0 which are greater than 20 and remaining keep as it is.
np.where(z>20,0,z)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [ 0,  0,  0,  0]]])

In [ ]:
# Multiply each value with 2
np.where(z,z*2,z*2)
z*2

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [18, 20, 22, 24]],

       [[26, 28, 30, 32],
        [34, 36, 38, 40],
        [42, 44, 46, 48]]])

In [ ]:
# Divide the values with 2 if it is divisible by 5 otherwise keep as it is 
np.where(z%5==0,z//2,z)

array([[[ 1,  2,  3,  4],
        [ 2,  6,  7,  8],
        [ 9,  5, 11, 12]],

       [[13, 14,  7, 16],
        [17, 18, 19, 10],
        [21, 22, 23, 24]]])

In [ ]:
# Logical Operators in Numpy
# AND---> &
# OR ---> |
# NOT --> ~

# Replace the value with 0 if it divisible by 2 and 5 both 
np.where((z%2==0)& (z%5==0),0,z)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9,  0, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19,  0],
        [21, 22, 23, 24]]])

In [ ]:
# Boolean Filtering 
# Syntax : var[condition]
 

ages=np.array([[35,22,75,45,15,26,60,33,51,67],[33,62,45,11,36,27,33,22,78,44]])
ages

array([[35, 22, 75, 45, 15, 26, 60, 33, 51, 67],
       [33, 62, 45, 11, 36, 27, 33, 22, 78, 44]])

In [ ]:
# Filter out those ages which are greater than 60.
ages[ages>60]

array([[False, False,  True, False, False, False, False, False, False,
         True],
       [False,  True, False, False, False, False, False, False,  True,
        False]])

In [ ]:
# Filter out the  ages which are less than 18
ages[ages<18]

array([15, 11])

In [ ]:
# Filter out the ages between 25 to 50.
ages[(ages>25)&(ages<50)]

array([35, 45, 26, 33, 33, 45, 36, 27, 33, 44])

In [ ]:
# Filter out the ages which are less than 18 and more than 60.
ages[~((ages<18) | (ages>60))]

array([35, 22, 45, 26, 60, 33, 51, 33, 45, 36, 27, 33, 22, 44])

In [ ]:
# Filter out the ages which are in between 18 to 60 
ages[(ages>18)&(ages<60)]

array([35, 22, 45, 26, 33, 51, 33, 45, 36, 27, 33, 22, 44])

# Practice questions 

1: Create a 1D NumPy array of numbers from 0 to 9

In [ ]:
np.arange(0,10)

array([6, 6, 3, 8, 6, 3, 2, 3, 3], dtype=int32)

2: Convert 1D array to 2D

In [ ]:
a=np.arange(8)
a.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

3: Print Array Attributes  
Instructions: Print the following attributes of the array:  
  
The shape of the array.  
The number of array dimensions.  
The size of each element in bytes. 
   
Given:  
import numpy as np  
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)  

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)

# The shape of the array.  
arr.shape
# The number of array dimensions.  
arr.ndim
# The size of each element in bytes. 
arr.itemsize

2

4: Create a 3×3 NumPy array of all True.

In [ ]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

5: Extract the documentation of NumPy’s arange() function.  

In [ ]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

6: Create a 1D array filled with zeros and another filled with ones.  

In [ ]:
print(f"Zeros :{np.zeros(5)} \nOnes: {np.ones(5)}")

Zeros :[0. 0. 0. 0. 0.] 
Ones: [1. 1. 1. 1. 1.]


7: Create a 1D array of 10 evenly spaced values between 5 and 50

In [ ]:
np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

8: Convert a Python list into a NumPy array  
  
Given:  
py_list = [1, 2, 3, 4, 5]

In [ ]:
list=[1,2,3,4,5]
np.array(list)

array([1, 2, 3, 4, 5])

9: Find the memory size of a NumPy array of numbers from 0 to 9.

In [ ]:
n=np.arange(0,10)
print(f"Array : {n}")
print(f"Memory size in bytes : {n.nbytes}")

Array : [0 1 2 3 4 5 6 7 8 9]
Memory size in bytes : 80


10: Reverse a 1D NumPy array

In [ ]:
n=np.arange(10)
n[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

11: Create a 3×3 identity matrix.

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12: Create a 4×4 array and extract its first row and last column.  

In [ ]:
n=np.arange(16)
a=n.reshape(4,4)
a

print(a)
print(f"First row : {a[0]}")
print(f"Last Column : {a.T[-1]}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
First row : [0 1 2 3]
Last Column : [ 3  7 11 15]


13: Extract Odd Rows and Even Columns.  

Problem Breakdown  
  
Rows: In programming, indexing starts at 0.   Odd-indexed rows would be rows 1 and 3.  
Columns: Even-indexed columns would be columns 0 and 2.  
Given:  
import numpy as np  
sampleArray = np.array([  
    [3, 6, 9, 12],  
    [15, 18, 21, 24],   
    [27, 30, 33, 36],  
    [39, 42, 45, 48],   
    [51, 54, 57, 60]  
])  

In [ ]:
n= np.array([  
    [3, 6, 9, 12],  
    [15, 18, 21, 24],   
    [27, 30, 33, 36],  
    [39, 42, 45, 48],   
    [51, 54, 57, 60]  
])
# print("New array with odd rows and even columns")
# a=np.array(n[1::2])
# b=a[0][0::2]
# c=a[1][0::2]
# np.array([b,c])

"""we can use both the method to run this program."""

arr=n[1::2,::2]
arr



array([[15, 21],
       [39, 45]])

14: Stack arrays horizontally  
Given:  
  
import numpy as np  
  
a = np.array([1, 2, 3])  
b = np.array([4, 5, 6])

In [ ]:
"""
The np.hstack() function stands for “horizontal stack.” It stacks arrays in sequence column-wise, effectively concatenating them along the second axis. For 1D arrays, this simply joins them end-to-end.

"""
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.hstack((a,b))
# a.tolist()+b.tolist()

array([1, 2, 3, 4, 5, 6])

15: Slice the first two rows and first two columns from a 4×4 array.

In [ ]:
a=np.arange(1,17,1)
b=a.reshape(4,4)

b[:2,:2]

array([[1, 2],
       [5, 6]])

16: Replace all odd numbers in a NumPy array with -1.  

In [ ]:
a=np.arange(1,11,1)
print(f"Original Array : {a}")
b=np.where(a%2!=0,-1,a)
print(f"Modified Array : {b}")

Original Array : [ 1  2  3  4  5  6  7  8  9 10]
Modified Array : [-1  2 -1  4 -1  6 -1  8 -1 10]


17: Get the indices of non-zero elements in an array  
Given:  
  
import numpy as np  
arr = np.array([1, 0, 2, 0, 3, 0, 4])  

In [ ]:
arr = np.array([1, 0, 2, 0, 3, 0, 4])

# for i in range(0,len(arr)):
#     if arr[i]!=0:
#         print(i, end=" ")

np.nonzero(arr)

(array([0, 2, 4, 6]),)

18: Find the common items between two arrays  
Given:  
import numpy as np  
  
a = np.array([1, 2, 3, 2, 8, 4, 2, 4])  
b = np.array([2, 4, 5, 6, 8])

In [ ]:
a = np.array([1, 2, 3, 2, 8, 4, 2, 4])
b = np.array([2, 4, 5, 6, 8])

# s=[]

# for i in b:
#     for j in a:
#         if i==j:
#             if i not in s:
#                 s.append(i)

# np.array(s)


"""we can use intersaction function """
c=np.intersect1d(a,b)
c


array([2, 4, 8])

19: Perform arithmetic operations on two NumPy arrays element-wise 
   
Add two NumPy arrays element by element.  
Multiply two NumPy arrays element by element.  
Given:  
  
import numpy as np  
  
a = np.array([1, 2, 3])  
b = np.array([4, 5, 6])



In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(f"Element-wise Sum: {a+b}")
print(f"Element-wise Multiplication: {a*b}")

Element-wise Sum: [5 7 9]
Element-wise Multiplication: [ 4 10 18]


20: Matrix multiplication  
Write a code to compute the dot product of two NumPy arrays  
  
Given:  
  
a = np.array([1, 2, 3])  
b = np.array([4, 5, 6])  

In [ ]:
a = np.array([1, 2, 3])  
b = np.array([4, 5, 6])
c=a*b
print(f"Dot product: {c.sum()}")
# print(f"Dot product: {np.dot(a,b)}")


Dot product: 32


21: Compute the mean, median, and standard deviation of a NumPy array  
Mean: Average of numbers.  
Median: Middle value when sorted.  
Standard Deviation: How spread out values are from the mean.  
Given:  

import numpy as np  
arr = np.array([10, 20, 30, 100, 200, 300])

In [ ]:
arr = np.array([10, 20, 30, 100, 200, 300])

print(f"Mean : {arr.mean()}")
print(f"Median : {np.median(arr)}")
print(f"Standard Deviation : {arr.std()}")

Mean : 110.0
Median : 65.0
Standard Deviation : 107.08252269472673


22: Remove common items from array  
Given:  
  
a = np.array([1, 2, 3, 4, 5])  
b = np.array([5, 6, 7, 8, 9])  

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

c=np.intersect1d(a,b)
a[a!=c]

array([1, 2, 3, 4])

23: Normalize a NumPy array (values between 0 and 1)  
Given:  
  
arr = np.array([10, 20, 30, 40, 50])

In [12]:
arr = np.array([10, 20, 30, 40, 50])
n= (arr - arr.min()) / (arr.max() - arr.min())

print(f"Normalize : {n}")


Normalize : [0.   0.25 0.5  0.75 1.  ]


24: Get the positions where elements of array a and b match.  
Given:  
  
import numpy as np  
  
a = np.array([1, 2, 3, 4, 5])  
b = np.array([1, 4, 3, 7, 8])

In [15]:
a = np.array([1, 2, 3, 4, 5])  
b = np.array([1, 4, 3, 7, 8])
# l=[]
# for i in range(0,len(a)):
#     if a[i]==b[i]:
#         l.append(i)

# np.array(l)

np.where(a==b)

(array([0, 2]),)

25: Extract numbers from an array  
Write a code to extract all numbers from an array that are between 5 and 10 (inclusive).  
  
Given:  
  
arr = np.arange(15)

In [26]:
arr=np.arange(15)
# np.where((arr>5) & (arr<10))

arr[(arr>=5) & (arr<=10)]

array([ 5,  6,  7,  8,  9, 10])

26: Create a random 3×2 matrix and find its maximum and minimum values  

In [37]:
# a=np.array([[1,2],[3,4],[5,6]])
# print("Maximum: ",np.max(a))
# print("Minimum: ",np.min(a))


a=np.array([[np.random.randint(1,10,2)],[np.random.randint(1,10,2)],[np.random.randint(1,10,2)]])
print(a)
print("Maximum: ",np.max(a))
print("Minimum: ",np.min(a))

[[[3 3]]

 [[6 9]]

 [[7 5]]]
Maximum:  9
Minimum:  3


27: Sorting a NumPy array based on a specific column 
  
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])  
  

.argsort(): This method is called on the selected column. It does not sort the column itself but returns the indices that would sort it. For the column [43, 22, 94], the sorted order would be [22, 43, 94], and the corresponding original indices are [1, 0, 2]. This is the output of .argsort().


In [74]:
sa = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
# s=sa[:, 1].argsort()
# sa[s]
print(sa)
sa[0,:].argsort()

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([0, 1, 2])